config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users

  root 'events#index'
   
  resources :events
  resources :attendances, only: [:new, :create, :index]
  resources  :users, only: :show 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  after_create :attendance_created

  def attendance_created
    UserMailer.attendance_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date,
    presence: {message: 'Date de départ obligatoire'}
    validate :start_date_is_past

  validates :duration, 
    presence: {message: 'Durée obligatoire'},
    numericality: {greater_than: 0}
    validate :is_duration_multiple_5

  validates :title,
    presence: {message: "Titre obligatoire"},
    length: {in: 5..140}

  validates :description,
    presence: {message: "Description obligatoire"},
    length: {in: 20..1000}

  validates :price,
    presence: {message: "Prix obligatoire"},
    numericality: {only_integer: true, greater_than: 0, less_than: 1000, message: "Le prix doit être compris entre 1 et 1 000"}

  validates :location,
    presence: {message: "Lieu obligatoire"}
  
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances
  belongs_to :admin, class_name: 'User'

  def start_date_is_past
    if start_date.past?
      errors.add(:start_date, "Date non valide")
    end
  end

  def is_duration_multiple_5
    if duration % 5 != 0
      errors.add(:duration, "La durée doit être un multiple de 5")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendances
  has_many :events, foreign_key: 'admin_id', class_name: 'Event', dependent: :destroy

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

def configure_devise_parameters
  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def new
  end

  def create
    # Before the rescue, at the beginning of the method
@stripe_amount = 500
begin
  customer = Stripe::Customer.create({
  email: params[:stripeEmail],
  source: params[:stripeToken],
  })
  charge = Stripe::Charge.create({
  customer: customer.id,
  amount: @stripe_amount,
  description: "Achat d'un produit",
  currency: 'eur',
  })
rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_order_path
end
# After the rescue, if the payment succeeded

  end

  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except:[:index]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new 
  end

  def create
    p "$"*60
    p params
    @event = Event.new(title:params[:title],description:params[:description],admin_id:current_user.id,duration:params[:duration],location:params[:location],price:params[:price],start_date:params[:start_date].to_datetime)
    p @event
    if @event.save
      redirect_to root_path, notice: "L'évènement '#{@event.title.capitalize}' a bien été créé ! Félicitation"
    else
      flash.now[:messages] = @event.errors.full_messages
      render new_event_path
    end
  end

  private 
  def event_params
    params.require(:event).permit(:title, :description, :duration, :price, :location, :start_date) 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show 
    @user = User.find(current_user.id)
  end

  def new
    @user = User.all
  end

 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/attendances/index.html.erb
<h1>Attendances#index</h1>
<p>Find me in app/views/attendances/index.html.erb</p>

app/views/attendances/new.html.erb
<!--jumbotron -->
<div class="jumbotron text-center" style="background-image: url(https://as1.ftcdn.net/v2/jpg/03/15/46/02/1000_F_315460238_r9VGtbJzt7emruDKEY2ouioFPdcbMKs4.jpg); background-size: 100%;">>
  <h1 class="display-4" style="color: #592316;"><strong>Inscription</strong></h1>
  <p class="lead" style="color: #592316;"><strong>Contribution pour ton évènement</p>
  <hr class="my-4">
  <p class="lead">
  </p>
</div>


<%= form_tag attendances_path do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <label class="amount">
    <span>Paiement de $5.00</span>
  </label>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Achat d'un produit"
    data-amount="500"
    data-locale="fr">
</script>
<% end %>

app/views/events/index.html.erb
<!--jumbotron -->
<div class="jumbotron text-center" style="background-image: url(https://as1.ftcdn.net/v2/jpg/03/15/46/02/1000_F_315460238_r9VGtbJzt7emruDKEY2ouioFPdcbMKs4.jpg); background-size: 100%;">>
  <h1 class="display-4" style="color: #592316;"><strong>Bienvenue !</strong></h1>
  <p class="lead" style="color: #592316;"><strong>Voici l'ensemble des évènements si tu souhaites participer n'hesites pas à te connecter</p>
  <hr class="my-4">
  <p class="lead">
  </p>
</div>

<!-- carte -->

<div class="row d-flex justify-content-evenly">
<%@events.each do |event|%>
  <div class="card" style="width: 18rem; background-color:#9CCED9" img src="https://media.istockphoto.com/vectors/man-taking-selfie-photo-on-smartphone-camera-casual-male-cartoon-in-vector-id1152621134?s=612x612" class="card-img-top" alt="...">
    <div class="card-body">
    
    <h5 class="card-title"><%=event.title%></h5>
    
    <p class="card-text"><%=event.description%></p>

    <p><%=event.start_date.to_date%></p>
    <a href=<%=event_path(event.id)%> class="btn btn" id="yellow-button">Afficher</a>
    <a href="#" class="btn btn" id="yellow-button">Participation</a>
    </div>
  </div>
   <%end%>

  <div class="card" style="width: 18rem; background-color:#9CCED9" img src="http://www.crecheoiseaubariole.net/gallery/20170802_093113.jpg" class="card-img-top" alt="...">
    <div class="card-body">
    
    <h5 class="card-title">Visite du musée</h5>
    
    <p class="card-text">Art / Deco</p>

    <a href="event_path" class="btn btn" id="yellow-button">Afficher</a>
    <a href="#" class="btn btn" id="yellow-button">Participation</a>
    </div>
  </div>

  <div class="card" style="width: 18rem; background-color:#9CCED9" img src="https://cdn.icon-icons.com/icons2/878/PNG/512/flower-with-leaves_icon-icons.com_68549.png" class="card-img-top" alt="...">
    <div class="card-body">
    
    <h5 class="card-title">Foire des plantes</h5>
    
    <p class="card-text">Stand de marchands de fleurs</p>

    <a href="event_path" class="btn btn" id="yellow-button">Afficher</a>
    <a href="#" class="btn btn" id="yellow-button">Participation</a>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<!--jumbotron -->
<div class="jumbotron text-center" style="background-image: url(https://as1.ftcdn.net/v2/jpg/03/15/46/02/1000_F_315460238_r9VGtbJzt7emruDKEY2ouioFPdcbMKs4.jpg); background-size: 100%;">
  <h1 class="display-4" style="color: #592316;"><strong>Super crée ton évènement !</strong></h1>
  <p class="lead" style="color: #592316;"><strong>Voici l'ensemble des conditions à remplir </p>
  <hr class="my-4">
  <p class="lead">
  </p>
</div>


<div class="container mb-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%=form_tag url_for(action: 'create'),class: "form-signin mt-3", method: "post" do %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Créer un évènement</h1>

        <div class='form-group'>
          <label>Titre</label><br>
          <%= text_field_tag 'title',"", class: 'form-control'%>
        </div>

        <div class='form-group'>
          <label>Description</label><br>
          <%= text_area_tag 'description',"", class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Durée</label><br>
          <%= number_field_tag 'duration',"", class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Prix</label><br>
          <%= number_field_tag 'price',"", class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Lieu</label><br>
          <%= text_field_tag 'location',"", class:'form-control'%>
        </div>  

        <div class='form-group'>
          <label>Date et heure de départ</label><br>
          <%= datetime_local_field_tag 'start_date',"", class:'form-control'%>
        </div>  

        <br>

        <div class='form-group'>

          <button type=submit class='btn btn-outline-warning'>Créer l'évènement</button>

        </div>
      <% end %>
      <%= link_to "Retour", root_path %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<!--jumbotron -->
<div class="jumbotron" img src="https://media.routard.com/image/39/2/paris-de-nuit.1564392.w630.jpg" style="background-color: #4B9DA6;">
  <h1 class="display-4" style="color: #735C3F;">Un super événement en prévision !</h1>
  <p class="lead">Si tu n'est pas encore inscrit... dépêche toi !</p>
  <hr class="my-4">
  <p class="lead">
  </p>
</div>

<div class='py-4'>
  <div class='container text-center'>
    <%if current_user.id != @event.admin.id && @event.users.exclude?(current_user.id)%>
      <br>
      <a class="btn btn-outline" id="yellow" href=<%=new_attendance_path(@event.id)%> role="button"><<<<  Inscription  >>>></a>
      <%elsif current_user.id == @event.admin.id%>
      <p>Pour en savoir plus sur mon évènement</p>
      <a class="btn btn-outline-warning" href=<%=attendance_path(@event.id)%>>Mon espace évènement</a>
    <%end%>
   </div> 
</div>

<div class='container text-center'>
  <div class='containerfluid my-5'>
    <h2><%=@event.title%> <span class='text-muted'>by <%=@event.admin.email%></span></h2>
    <hr>
    <p>Lieu : <%=@event.location%></p>
    <p>Date de début : <%=@event.start_date%></p>
    <p>Date de fin : <%=@event.end_date%>
    <hr>
    <p>Nombre de personnne(s): <%=@event.attendances.size%>
    <p> Prix : <%=@event.price%> €
    <hr class='border-3 border border-warning'>
    <p>Description:</p>
    <p class='mx-5'>>>> <%=@event.description%></p>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>On se retrouve ou?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--Favicon -->
    <link rel="icon" type="image/svg+xml" href=https://image.freepik.com/vecteurs-libre/icone-boussole-moderne_1284-3645.jpg>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!--CSS  Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <!--HEADER navbar -->

  <header>
<nav class="navbar navbar-expand-lg fixed-top" style="background-color: #9CCED9; border-color:#27538C;">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%=root_path%>"style="color: #27538C;"><span class="yellow">On</span> se Retr<span class="yellow">ou</span>vE ?</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" style="color: #27538C;"aria-current="page" href="<%=root_path%>">Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" style="color: #27538C;"aria-current="page" href="<%=new_event_path%>">Créer un évenement</a>
            
      </ul>
      </div> 
      
         <div class="dropdown">
              <% if user_signed_in?  %>
                <button class="btn btn-outline-warning dropdown-toggle" type="button" id="yellow-button" data-bs-toggle="dropdown" aria-expanded="false">Mon profil</button>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="yellow-button">
                  <li><a class="dropdown-item" href="<%=user_path(current_user.id)%>">Mon profil</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="<%=destroy_user_session_path%>" data-method='delete' >Se déconnecter</a></li>
              </ul>
              <% else %>
                <button class="btn btn-outline-warning dropdown-toggle" type="button" id="yellow-button" data-bs-toggle="dropdown" aria-expanded="false">S'inscrire/Se connecter</button>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="yellow-button">
                  <li><a class="dropdown-item" href='<%=new_user_registration_path%>'>S'inscrire</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="<%=new_user_session_path%>">Se connecter</a></li>
                  </ul>
                <%end%>
            </div>
  </div>
</nav>         
  </header>  


  





    <!--Alertes -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>





    <%= yield %>


    <!--Footer -->
    <footer class="footer mt-auto py-1 bg-light text-center fixed-bottom ">
      <div class="container">
        <span class="text-muted">© Created by The Power Coders & THP</span>
      </div>
    </footer>

    <!--JS Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  </body>
</html>

app/views/users/show.html.erb
<div class="jumbotron text-center" style="background-image: url(https://as1.ftcdn.net/v2/jpg/03/15/46/02/1000_F_315460238_r9VGtbJzt7emruDKEY2ouioFPdcbMKs4.jpg); background-size: 100%;">
  <h1 class="display-4" style="color: #592316;"><strong>Super crée ton évènement !</strong></h1>
  <p class="lead" style="color: #592316;"><strong>Voici l'ensemble des conditions à remplir </p>
  <hr class="my-4">
  <p class="lead">
  </p>
</div>


<div class="container bootstrap snippets bootdey carte">
    <div class="panel-body inf-content">
        <div class="row">

        <div class="col-md-4">
            <img alt="" style="width:600px;" title="" class="img-circle img-thumbnail isTooltip" src="https://bootdey.com/img/Content/avatar/avatar7.png" data-original-title="Usuario"> 
            <ul title="Ratings" class="list-inline ratings text-center">
                <li><a href="#"><span class="glyphicon glyphicon-star"></span></a></li>
                <li><a href="#"><span class="glyphicon glyphicon-star"></span></a></li>
                <li><a href="#"><span class="glyphicon glyphicon-star"></span></a></li>
                <li><a href="#"><span class="glyphicon glyphicon-star"></span></a></li>
                <li><a href=""><span class="glyphicon glyphicon-star"></span></a></li>
            </ul>
        </div>

        <div class="col-md-6">
            <br>
            <div class="table-responsive">
            <table class="table table-user-information">
                <tbody>
                     <tr>    
                        <td>
                            <strong>
                                <span class="glyphicon glyphicon-user  text-primary"></span>    
                                <p>Prénom</p>                                                
                            </strong>
                        </td>
                        <td class="text-primary">
                            <span class='yellow'><%=@user.first_name%></span>    
                        </td>
                    </tr>
                    <tr>        
                        <td>
                            <strong>
                                <span class="glyphicon glyphicon-cloud text-primary"></span>  
                                <p>Nom</p>                                                
                            </strong>
                        </td>
                        <td class="text-primary">
                            <span class='yellow'><%=@user.last_name%></span>  
                        </td>
                    </tr>

                    <tr>        
                        <td>
                            <strong>
                                <span class="glyphicon glyphicon-envelope text-primary"></span> 
                                <p>Email</p>                                                
                            </strong>
                        </td>
                        <td class="text-primary">
                            <span class='yellow'><%=@user.email%></span> 
                        </td>
                    </tr>
                       
                        <td>
                            <strong>
                                <span class="glyphicon glyphicon-calendar text-primary"></span>
                                <p>Description</p>                                                
                            </strong>
                        </td>
                        <td class="text-primary">
                             <span class='yellow'><%=@user.description%></span>
                        </td>
                    </tr>   
                          <a href=<%=edit_user_registration_path%>><button type="button"class="btn btn-outline btn-lg px-4 me-sm-3 my-3"id="yellow-button">Actualise ou modifie ton profil</button></a>                                                       
                </tbody>
            </table>
            </div>

        </div>
        <h2>Les évèments crées :</h2>
  <div class="row">
    <%@user.events.each do |event|%>
      <div class="col-md-4 p-5">
        <h2><%=event.title%></h2>
        <p><%=event.description%></p>
        <p><%=event.start_date.to_date%>
        <p><a class="btn btn-outline-warning" href="href=<%=event_path(event.id)%>" role="button">Détails »</a></p>
      </div>
    <%end%>
  </div>  
    </div>
</div>